# 追加対象はbaseの中とapiVersion、kind、metadata.nameのどれかは違う内容にすること(全て同じだと既にbaseにありますエラーになる)
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deployment-test
spec:
  replicas: 1
  ports:
  - containerPort: 1010