apiVersion: kustomize.config.k8s.io/v1beta1
kind: Service
metadata:
  name: sample
spec:
  type: NodePort
  selector:
    app: sample
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 8080