apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# nginx1とnginx2で異なる名前(metadata.nameを指定しているため、buildすると2つのDeploymentを作成できる)
# nginx1とnginx2でapiVersion、kind、metadata.nameが全て一致しているとエラーになる
resources:
 - ../../base/nginx1
 - ../../base/nginx2