# 上書き対象はbaseの中とapiVersion、kind、metadata.nameは同じにすること
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Deployment
metadata:
  name: sample
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80